CursoDjango/CursoDjango/urls.py
from django.contrib import admin
from django.urls import path, re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.ejemplo.urls')),
]

CursoDjango/applications/ejemplo/urls.py
from django.urls import path
from . import views


app_name = "usuario_app"

urlpatterns = [

    path('', views.PruebaView.as_view(), name= 'inicio'),
    path('listar-usuarios/', views.PruebaListView.as_view(), name= 'listarusuario'),
    path('crear-usuarios/', views.PruebaCreateView.as_view(), name= 'crearusuario'),
    path('actulizar-usuarios/<pk>', views.PruebaUpdateView.as_view(), name= 'actulizarusuario'),
    path('eliminar-usuarios/<pk>', views.PruebaDeleteView.as_view(), name= 'eliminarusuario'),

]

CursoDjango/applications/ejemplo/models.py
from django.db import models

# Create your models here.


#la bade de datos tendra nombres, apellidopaterno  y apellido materno

class Usuario(models.Model):

    nombre = models.CharField('nombre', max_length=50)
    apellidoPaterno = models.CharField('apellidop', max_length=100)
    apellidoMaterno = models.CharField('apellidom', max_length=100)
   
    def __str__(self):
        return str(self.id) + '-' + self.nombre + '-' + self.apellidoPaterno

 

CursoDjango/applications/home/models.py
from django.db import models

# Create your models here.

CursoDjango/applications/ejemplo/forms.py
from django import forms

from .models import Usuario


class UsuarioForm(forms.ModelForm):

    class Meta:

        model = Usuario
        fields = (
            'nombre',
            'apellidoPaterno',
            'apellidoMaterno',
        )

CursoDjango/applications/ejemplo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView , DetailView, CreateView , TemplateView, UpdateView, DeleteView
from .models import Usuario
from .forms import UsuarioForm

#CRUD = CREATE, READ, UPDATE Y DELETE


class PruebaView(TemplateView):
    template_name = 'inicio.html'


class PruebaListView(ListView):
    template_name = 'listausuario.html'
    context_object_name = 'listarusuario'
    model = Usuario

class PruebaCreateView(CreateView):
    template_name = 'createusuario.html'
    context_object_name = 'createusuario'
    model = Usuario
    form_class = UsuarioForm
    success_url = reverse_lazy('usuario_app:listarusuario')
    def form_valid(self, form):
        usuario = form.save(commit=False)
        usuario.save
        return super(PruebaCreateView,self).form_valid(form)

class PruebaUpdateView(UpdateView):
    template_name = 'updateusuario.html'
    context_object_name = 'updateusuario'
    model = Usuario
    form_class = UsuarioForm
    success_url = reverse_lazy('usuario_app:listarusuario')
    def form_valid(self, form):
        return super(PruebaUpdateView,self).form_valid(form)
    
class PruebaDeleteView(DeleteView):
    model = Usuario
    template_name = 'deleteusuario.html'

    success_url = reverse_lazy('usuario_app:listarusuario')

CursoDjango/applications/home/views.py
from django.shortcuts import render

# Create your views here.

CursoDjango/templates/createusuario.html
<h1>Crear Usuarios</h1>

<form  method="POST" enctype="multipart/form-data">{% csrf_token %}

    {{form.as_p}}


<button type = submit> Registrar</button>

</form>

CursoDjango/templates/deleteusuario.html
<h1>Eliminar Usuario</h1>


<form class="cell" method="POST">{% csrf_token %}

<p>Estas seguro que deseas eliminar al usuario: {{object.nombre}}, {{object.apellidoPaterno}}  {{object.apellidoMaterno}}  </p>

<button type = submit> Si, Eliminar</button>
</form>

CursoDjango/templates/inicio.html
<h1>Este es un Template View</h1>

<a href="{% url 'usuario_app:listarusuario' %}">Listar Usuarios</a>

<a href="{% url 'usuario_app:crearusuario' %}">Crear Usuarios</a>

CursoDjango/templates/listausuario.html
<h1>Lista de usuarios</h1>

<ul>
    {% for e in listarusuario %}
    <li>
        {{e.nombre}} 
        {{e.apellidoPaterno}}
        {{e.apellidoMaterno}} -
        <a type="button" href="{% url 'usuario_app:actulizarusuario' e.id %}" >Editar</a>

        <a type="button" href="{% url 'usuario_app:eliminarusuario' e.id %}" >Eliminar</a>
    </li>
    {% endfor %}
</ul>

CursoDjango/templates/updateusuario.html
<h1>Actualizar Usuario</h1>

<form class="grid-x callout grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}

    {{form.as_p}}

    <button type = submit> Actualizar</button>

</form>